### ISSUE TITLE
SED: can't read /home/.../local/lib/refprop/FOR/PASS_FTN.f: No such file or Directory 

### ISSUE THREAD

**Issue by prat777** [BenThelen/python-refprop#15]
Hello CoolProp Team, 

I Upgraded my system to a favorable Dell poweredge R710 with Ubuntu 18.04 LTS. I performed the wine install for the NIST2310.EXE and then attempted to execute the rp2so bash script, but it kept getting hung up on this error indicated in the attachment. I checked out line 80 in the file and everything seems proper, so I'm not sure if PASS_FTN.f is a file that is not present in REFPROP 10.0 directory, or has been misplaced in the wine-baed refprop directory; so I attempted to search for its existence with no yield. And so I was wondering how I would go about this problem.

Regards, 

Prathamesh Patil 

Attachments:
(1) REFPROP version 10.0

(2) Screeshot of Terminal
![image](https://user-images.githubusercontent.com/4643760/71531509-05d50d00-28bd-11ea-88b6-4c25d3d1351e.png)

**Comment by birdol** [comment]
where is  REFPROP version 10.0？
