### ISSUE TITLE
License

### ISSUE THREAD

**Issue by mwoc** [BenThelen/python-refprop#3]
Hi, I'm using your refprop api/wrapper in a project of mine and am considering publishing my project bundled with your api. Would this be fine with you, and if so, could you perhaps add a license to your project so it's more clear?

**Comment by BenThelen** [comment]
Maarten,

I'd never given any thought about this, I have looked this up in google and concluded I'm fine with a BSD licence. Anybody can use the code as long as it's not commercialized. 

I'll add this soonest.

Ben

**Comment by BenThelen** [comment]
License has been added.
