### ISSUE TITLE
[bug] in wmol function definition

### ISSUE THREAD

**Issue by kevinholst** [BenThelen/python-refprop#5]
``` python
    if platform.system() == u'Linux':
        _rp.wmoldll_(_x,
                    ctypes.byref(_wmix))
    elif platform.system() == u'Windows':
        _rp.WMOLdll(_x,
                        ctypes.byref(_wmix))
```

I believe the Linux function should be:

``` python
        _rp.wmol_(_x,
```

Thanks so much for this great piece of coding!

**Comment by BenThelen** [comment]
Yes and No,
Yes to be consistence with the other API calls
No, because the Nist fortran code for this function does not return the wmix value. As such the python API cannot (technically it can) obtain this. Hence the code utilise the windows dll function.

thanks for the update
