### ISSUE TITLE
How long will the test() function last?

### ISSUE THREAD

**Issue by uqzcpo** [BenThelen/python-refprop#6]
I try to run the following code:
import refprop
refprop.test()

then the interpreter gives no response for a long time and nothing displays on the screen. 
I use refprop 9.0.
Are there any tutorials for this API?

**Comment by BenThelen** [comment]
The refprop python API has been updated, this should now be working smoothly, depending on your hardware the test function should run between 10 to 30 sec. a print out is beeing displaced while the test is being executed.
